--- 2025-11-17 20:24:34 | INFO     | __main__:main:220 - CAPTURING MOKU STATE 2025-11-17 20:24:34 | INFO     | __main__:main:221 - ============================================================ 2025-11-17 20:24:34 | INFO     | __main__:capture_moku_state:75 - Output directory: b 2025-11-17 20:24:34 | INFO     | moku_cli_common:time_operation:201 -   Getting instrument list: 17.12 ms 2025-11-17 20:24:34 | INFO     | __main__:capture_moku_state:80 - Current configuration: ['Oscilloscope', 'CloudCompile'] 2025-11-17 20:24:34 | INFO     | __main__:capture_moku_state:89 - Saving MIM-level configuration... 2025-11-17 20:24:34 | INFO     | moku_cli_common:time_operation:201 -   Saving MIM configuration: 15.83 ms 2025-11-17 20:24:34 | SUCCESS  | __main__:capture_moku_state:94 - Saved MIM config to b/mim_config.mokuconf 2025-11-17 20:24:34 | INFO     | __main__:capture_moku_state:97 - Saving individual instrument configurations... 2025-11-17 20:24:34 | INFO     | __main__:capture_moku_state:103 -   Slot 1: Oscilloscope 2025-11-17 20:24:35 | INFO     | moku_cli_common:time_operation:201 -     Getting Oscilloscope instance: 525.24 ms 2025-11-17 20:24:35 | INFO     | moku_cli_common:time_operation:201 -     Saving Oscilloscope settings: 521.91 ms 2025-11-17 20:24:35 | SUCCESS  | __main__:capture_moku_state:122 -     Saved to b/slot1_Oscilloscope.mokuconf 2025-11-17 20:24:35 | INFO     | __main__:capture_moku_state:103 -   Slot 2: CloudCompile 2025-11-17 20:24:35 | INFO     | moku_cli_common:time_operation:201 -     Getting CloudCompile instance: 0.19 ms 2025-11-17 20:24:35 | ERROR    | __main__:capture_moku_state:125 -     Error saving CloudCompile: Bitstream package path is required for Cloud Compile 2025-11-17 20:24:35 | INFO     | __main__:capture_moku_state:133 - Saving metadata... 2025-11-17 20:24:35 | INFO     | moku_cli_common:time_operation:201 -   Collecting device metadata: 0.22 ms 2025-11-17 20:24:35 | ERROR    | __main__:main:236 - Failed to capture state: 'MultiInstrument' object has no attribute '_ip' Traceback (most recent call last): ---- Almost worky